# To create an environment from the following requirements use
# conda env create -f path/to/environment.yml

# Whereas to update the environment use the following commands
# conda activate flatland
# conda env update -f environment.yml --prune

name: flatland
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  # Visualization
  - cairosvg
  - pycairo
  - tk
  - pip
  - pip:
    # The world simulation
    - flatland-rl
    # Notebooks
    - jupyter
    - ipycanvas
    # Neural networks
    - tensorflow
    # To keep the env clean
    - pip-autoremove
